### ISSUE TITLE
Make changes to handle PD & PPD status. 

### ISSUE THREAD

**Issue by JasonCTang** [bcgov/SIMS#2001]
**Describe the task**
Change current PD flag from True/False to instead store a value to indicate the status: 
 - Not requested
 - Requested
 - PD (permanent) 
 - PPD (temporary) or not
 - Declined

**Additional context**
- PPD is a new status from ATBC.  Any PD information coming from SFAS legacy data will be PD (permanent) status.
- ATBC Result URL: https://test.at-bc.ca/api/sfas?sfasDate=yyyy/mm/dd    (GET) 
- Link to API Schema (Ask Ann)
- Do not change workflow at this time.

**Acceptance Criteria**
- [x] Modify database, add new column
- [x] Adjust the Student profile (currently read from dates, but will now read from ENUM)
- [x] Adjust the application with the status info (currently read from dates, but will now read from ENUM)
- [x] ATBC API integration (API request schedulers)
- [x] Create E2E tests
- [x] Match student in ATBC Result JSON using the following fields (Line numbers in brackets correspond to image below) SIN (4), last name (10) and DOB (13).
![MicrosoftTeams-image (2).png](https://images.zenhubusercontent.com/6398d78b550c6ab79f2d32ac/d2b808e6-636f-4f60-ba0d-d417c93569de)

**Comment by dheepak-aot** [comment]
## Student Applying for disability status multiple time

Current understanding as per  with @JasonCTang, student requests disability status only once in our SIMS application. In case they want to apply again because of something happened to them later after losing their disability status(PPD), they update ATBC directly and ATBC will be updating the student disability status which we read on daily basis through their response API.
