### ISSUE TITLE
Remediate high risk vulnerabilities from WAVA report

### ISSUE THREAD

**Issue by JasonCTang** [bcgov/SIMS#2006]
**Describe the task**
Review and remediate the high risk vulnerabilities from the attached WAVA report

**Acceptance Criteria**
- [ ] Fix pagination vulnerability.
- [ ] Deploy fixes to Test for re-scan.

**Additional context**
[https://app.zenhub.com/files/319429847/4acbc6e6-7de0-4a90-b056-50e69ea61aed/download](https://app.zenhub.com/files/319429847/4acbc6e6-7de0-4a90-b056-50e69ea61aed/download)

**Comment by andrewsignori-aot** [comment]
The `API Mass Assignment` was not considered critical to fix for the v1.0.0 release based on the below.
- All data received by the API is mapped through specific DTOs;
- The API framework ([Nestjs](https://docs.nestjs.com/)) `whitelist` configuration is enabled which ensures that any additional property received will be removed before the actual process happen. More information on https://docs.nestjs.com/techniques/validation.
- The team agreed to have the configuration `forbidNonWhitelisted` also enabled for the upcoming releases ensuring that the API will return an error instead of a success 200 which will comply better with the Wava requirements. The decision was made based on the fact that globally enabling `forbidNonWhitelisted` right now can potentially introduce side effects and the application may not be fully tested prior to release v1.0.0.
