### ISSUE TITLE
Student Application Update- Change Separated / Divorced / Widowed Students to 'Independent' Status

### ISSUE THREAD

**Issue by HRAGANBC** [bcgov/SIMS#2165]
@Michelle to clean up AC

**@Biz** Confirm with some screenshots the interface workflow impacts.
Verify how workflow is currently moving.

SABC Policy states that if a student is separated, divorced, or widowed, they are assessed as an independent student. 

**Current Behavior**
If a student selects 'separated/divorced/widowed' as their marital status, but other aspects of their application indicate they would be considered dependant, then student is treated as dependant and the dynamic application form will prompt student to input parental info. 

**Expected Behavior**
 If a student selects separated/divorced/widowed as their marital status, they should be considered independent REGARDLESS of whatever other questions they've answered. The dynamic application form should NOT request that they provide spousal/partner info, nor should it collect parental info. 

**Acceptance Criteria**
-If the student selects " other" then ?
- [ ] If Student Answers 'Yes to  Separated / Divorced / Widowed Students' through the Independent Workflow (Not the Dependant Workflow) This rule overrides any previous depandant designations.

**Comment by dheepak-aot** [comment]
## Current behavior 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaFFKIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--ed0a17be417ab7c811f01207dad1a4da85ae39b4/image.png)

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaFVKIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--ed8207587c2eeff327306eb9817aaea86d55e2f5/image.png)

## Expected Behavior
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaGdKIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--512b90c53df8ebfbee9556d569d67016370e6887/image.png)

**Comment by dheepak-aot** [comment]
## Form IO code changes

Update the calculated value of `showParentInformation` to remove the condition which checks `relationshipStatus === 'other'`

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaDhKIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--aab7bf956aa56a4822ec57f4110db732d7cfea8f/image.png)


## Assessment gateway workflow changes

Current condition for Dependent, Independent and Married

Dependent:  (studentDataRelationshipStatus = "single" or studentDataRelationshipStatus = "other") and studentDataDependantstatus = "dependant"

Independent:  (studentDataRelationshipStatus = "single" or studentDataRelationshipStatus = "other") and studentDataDependantstatus = "independant"

Married: studentDataRelationshipStatus = "married"
