### ISSUE TITLE
Analysis ticket: Remove Part-Time Questions from Application

### ISSUE THREAD

**Issue by JasonCTang** [bcgov/SIMS#2236]
Perform analysis on #2172.
Analyze the impact of removal of questions on the workflow.
Identify the questions that are being removed for part time, but kept for full time and analyze the logic.
Ensure we have the upcoming ticket to execute question removal. Update #2172 with expected ACs to remove the questions.

**Comment by ann-aot** [comment]
**_Analysis_**
Remove the following questions entirely from the PT application (this means removing the question on the application form presented through the interface, as well as any resulting logic attached to these questions)
- [ ]  “At the time of your course study start date, will you have been out of high school for 4 years?” (Yes/No)

-  - **_It is not used in assessment, it is used for the `showParentInformation` calculation in form, but the logic is only for FT application. If it is PT, then the `showParentInformation` is `false`. Which is used for the `dependantstatus` logic (it is only for FT, not for PT)_**

- [ ] “When did you graduate high school” (calendar entry)

- - **_Only used in FT assessment logic, but as a part of it it is retrieved in the `load assessment` for both PT and FT ?? Check if empty `whenDidYouGraduateOrLeaveHighSchool` it will effect the  `load assessment` for PT._**

- [ ]  “In time since leaving high school, have you spent two periods of 12 consecutive months each, in the full time labour force?”

-  - **_Not used in assessment/formio calculation._**

- [ ] “Will you receive voluntary contributions from parents…”

- - **_Only used in FT assessment logic, but as a part of it it is retrieved in the `load assessment` for both PT and FT ?? Check if empty `parentvoluntarycontributionsCosts` it will effect the  `load assessment` for PT._**

-  [ ] “Will you have government funding …

- - **_Only used in FT assessment logic, but as a part of it it is retrieved in the `load assessment` for both PT and FT ?? Check if empty `governmentFundingCosts` it will effect the  `load assessment` for PT._**

- [ ] “Will you have non-government funding…

-  - **_Only used in FT assessment logic, but as a part of it it is retrieved in the `load assessment` for both PT and FT ?? Check if empty `nongovernmentfundingCosts` it will effect the  `load assessment` for PT._**

-  [ ] “If you must relocate to a different city to attend school…”

-  - **_Not used in assessment/formio calculation._**

- [ ] “is your partner employed full time or part time” (remove from student self-declaring on behalf of their spouse, and also when spouse answers question themselves)

-  - **_Not used in assessment/formio calculation._**

- [ ] “Child support/spousal support”

-  - **_Only used in FT assessment logic, but as a part of it it is retrieved in the `load assessment` for both PT and FT ?? Check if empty `childsupportCosts` `studentDataChildSupportAndOrSpousalSupport` it will effect the  `load assessment` for PT._**

- [ ] "Do you want to submit an exemption request for exceptional expenses"

-  - **_Not used in assessment/formio calculation._**

- [ ] Do you want to be assessed with this year's income"

-  - **_Not used in assessment/formio calculation._**

- [ ] "Will you have merit-based scholarships or needs-based bursaries...."

-  - **_Only used in FT assessment logic, but as a part of it it is retrieved in the `load assessment` for both PT and FT ?? Check if empty `scholarshipsreceviedCosts` `studentDataScholarshipAmount` it will effect the  `load assessment` for PT._**

-  [ ] “Will you be living in a room paid for by your parents/step-parents
- -  _**The next qn in the list is actually the sub question of this one, so, when the this is removed the next qn, will also be removed**_

- - Actual qn is, [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaUtDIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--173c87ce9a6fed839586037adc01b0aea1d558bd/image.png)

-  - **_Only used in FT assessment logic, but as a part of it it is retrieved in the `load assessment` for both PT and FT ?? Check if empty `livingWithParents` it will effect the  `load assessment` for PT._**

-  [ ] “Will you be paying room and board to your parents…”

-  - **_Only used in FT assessment logic, but as a part of it it is retrieved in the `load assessment` for both PT and FT ?? Check if empty `livingathomeRent` it will effect the  `load assessment` for PT._**


-  [ ] Do you want to be assessed for additional transportation costs

-  - **_Not used in assessment/formio calculation._**

**Comment by ann-aot** [comment]
If a variable its not present in the load assessment, it will not effect the workflow. So removing the above question from the P.T application will not effect the workflow
