### ISSUE TITLE
Determine Equifax Integration Readiness / Determine Implementation Plan

### ISSUE THREAD

**Issue by mzmichellesmith** [bcgov/SIMS#228]
Tasks
- [x] Validate Equifax Documentation- check calls that they have provided.
- [x] Validate Endpoint Connection
- [x] Submit for access to their environment
- [x] Review Sandbox Environment -Not usable yet
- [ ] Determine the data that is sent back

Acceptance Criteria
- [x] Validate Successful Call (Postman) 
- [x] Determine Implementation Next Steps (Plan)
- [x] Update Architectrue Diagram

**Comment by andrewsignori-aot** [comment]
Please find below the current integration status.

Considering the below TEST(UAT) environment, please find also below what we are trying and what are the questions so far. The questions are highlighted in **bold**.

![image.png](https://images.zenhubusercontent.com/5fcebe3c076e6aaed83693fb/30c19846-41dd-464f-8b86-32099596858c)

Using the server with public IP 142.34.134.52 (linda.dmz) and trying to execute a GET on endpoint https://api.uat.equifax.ca/logs/v1 results in the below error message.
**Question: Is there a way to confirm if there is some issue in our end or on Equifax side? Apparently the server being used for tests has the correct public IP in the white list.** 

![image.png](https://images.zenhubusercontent.com/5fcebe3c076e6aaed83693fb/a42ae087-679e-4d11-a91d-d1dfaf8b90dc)

The documentation states that the below request should be made in order to request a new token as shown below.

![image.png](https://images.zenhubusercontent.com/5fcebe3c076e6aaed83693fb/c825fe5f-7bf4-4614-990f-fa4a858370ce)

But the Postman Collection is also defined using a “Basic Auth” that will produce a different request, like below.
**Question: What is the correct request to retrieve the token?**

curl --location --request POST 'https://api.uat.equifax.ca/v2/oauth/token' \
--header 'Content-Type: application/x-www-form-urlencoded' \
**--header 'Authorization: Basic <encoded data>' \**
--data-urlencode 'grant_type=client_credentials' \
--data-urlencode 'scope=https://api.equifax.ca/inquiry/1.0/sts'

We are going to use the Equifax to primarily request financial data for a consumer and it seems that XML is the preferable way (EQUIFAX_UAT_STS_XML_CONSUMER).
It seems that this request has a InputSegments payload with a XML on it.
**Question: where can we find documentation about this specific request?
Question: is this the correct endpoint to retrieve consumer financial data (https://api.uat.equifax.ca/inquiry/1.0/sts)?**

![image.png](https://images.zenhubusercontent.com/5fcebe3c076e6aaed83693fb/3af55585-b3bd-481a-b128-e9c5bc84c139)

**Comment by andrewsignori-aot** [comment]
During a working session with the Equifax support/dev team, we were able to make the successful authentication and also request a credit report from the API.

For the authentication, some documentation available has the incorrect request. We must assume that the correct one is the one present in the Postman collection, as shown below.

![image.png](https://images.zenhubusercontent.com/5fcebe3c076e6aaed83693fb/5380aad8-e157-4991-a0a5-05544312aa7f)

![image.png](https://images.zenhubusercontent.com/5fcebe3c076e6aaed83693fb/bfc62135-7d9d-4ddd-800c-fb4dfbb1d33d)

We also confirmed during the meeting that the preferred method to be used to retrieve the credit information is the below one, also presented in the JSON collection. 

![image.png](https://images.zenhubusercontent.com/5fcebe3c076e6aaed83693fb/d9fe3190-0552-4906-8028-a83c69ecdc50)

The above method uses an XML payload that we were able to submit for one particular set of data once we provided the Ministry "Customer Code", "CustomerNumber" and "Security code" (not shared here for security purposes).

During the meeting, we also requested specific documentation about how to properly create the XML payload and also how to correctly find the information that we need in the response. They are going to share the documentation with us as soon as possible.
