### ISSUE TITLE
Finastra - File name change

### ISSUE THREAD

**Issue by andrepestana-aot** [bcgov/SIMS#2479]
**Description of Task**
The naming convention for the PT eCert SEND file and the PT eCert FEEDBACK file need to be confirmed. Specifically, need to confirm that file names produced by SIMS are not identical to those produced by SFAS. 

**Context:** 
Currently, SFAS produces a PT eCert SEND file with naming convention: TPBC.EDU.PTCERTS.Dyyyyjjj.001

**Acceptance Criteria:**
- [x] Change the PT eCert SEND file naming convention to: TPBC.EDU.NEW.PTCERTS.Dyyyyjjj.001 (once in production, the 'T' from the beginning will be dropped)

**Comment by andrewsignori-aot** [comment]
@HRAGANBC the feedback files were adjusted in the last ticket to include the "NEW".
I did not get why we need the temporary "T" for the e-Cert if also contains the "NEW". We can leave this for a grooming also.
Is the T the same that indicates the environment for other ESDC integrations?

**Comment by HRAGANBC** [comment]
@andrewsignori-aot

The 'T' is used to distinguish TEST files from PRODUCTION files, since the SFTP servers which are used to relay these Test files are the same servers/folders containing all the real production files, and they need to make sure they're clearly marked. 

I can't comment on ESDC integrations since I've never been exposed to those processes, but my gut instinct is yes, the T is common usage to indicate TEST files. 

OK if the Feedback file name is already adjusted then the First AC is done, I jsut wasnt sure if that was still outstanding.

**Comment by andrewsignori-aot** [comment]
@HRAGANBC ESDC integrations are e-Cert, Feedback, SIN Validation, and others. They already use different letters for different environments, so we should be good.
If the ticketed is ready it can be moved to the appropriate lane, anything but "new issues".
