### ISSUE TITLE
Ensure offering parent id is always present

### ISSUE THREAD

**Issue by andrewsignori-aot** [bcgov/SIMS#2488]
While creating a new offering or cloning an offering, ensure that the parent offering ID is always present.
This will required to ensure that IER12 always has an offering parent ID present to allow better tracking by the institution.

**Acceptance criteria**
- [x] While an offering is created, ensure that the parent id is also populated with the newly created id.
- [x] Check places cloning offerings and also ensure that they have the parent id populated.
- [x] Display the Parent offering ID on the Offering Form
- [x] Assess the possibility to change parent offering id column to be mandatory and populating it - [_**decision added in the comment below**_]

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeURqQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f999baa54b3a2f95db2d0094d40f5a1f592d678a/image.png)

**Comment by ann-aot** [comment]
**_Assess the possibility to change parent offering id column to be mandatory and populating it_**
when offering is created via bulk upload, we are doing `typeorm .insert()`, with which we cannot assign the primary key to the parent offering id, since the offering does not exist at that point.
`error: error: column "id" does not exist` is the error DB is throwing, when we try to do so.
And we don't want to go that `.save()`, which will solve issue, because of the performance issue that was detected during load test.
So, we decided to keep the insert with the parent offering id (which means the parent offering id can't be a mandatory field), And once the offerings are created, we do a bulk update to update the parent offering id.
