### ISSUE TITLE
Hide FT Programs for PT release

### ISSUE THREAD

**Issue by HRAGANBC** [bcgov/SIMS#2524]
**Description of Task**
Hide all FT-only programs and all FT offerings from the Student application dropdown menu so they are unavailable at the initial SIMS launch date. 

**Context:**
- Institutions will continue inputting FT programs and offerings, and should continue to view/manage them from within their account
- Student applications must be restricted to PT-only offerings to ensure that no FT applications inadvertently get submitted. 

**Acceptance Criteria**
- [x] Hide all FT-only programs from the student dropdown menu
- [x] Hide all FT offerings from the student dropdown menu
- [x] Make solution environmentally aware (based on configuration) so that it can be toggled off/on for test/prod environment.
- [x] Ensure that application submit/draft will accept only PT applications when the toggle is on. Execute the check based on the toggle.
- [x] Ensure that the dropdown for PT/FT in the student application will be hidden and the default value will be PT.
- [x] Disable FT schedulers based on toggle (off/on).

**Comment by guru-aot** [comment]
Leverage the isActive flag in queue configurations trying to make the queues configurable.

**Comment by andrewsignori-aot** [comment]
As pointed out by @dheepak-aot, the system currently allows a part-time offering to be created for a Full-time program. It will generate a Pending offering but the Ministry will have the power to approve it. This specific offering will not be selectable because the program itself would never be displayed to the student as it is right now.
<img width="833" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGZ2QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--eb21a849aa7fd3a18ce872032941fd1c329f6e98/image.png" alt="image.png" />

Right now we will not be considering this scenario and the ticket will be implemented as stated in the current AC: "Hide all FT-only programs from the student dropdown menu".

@CarlyCotton will follow up from the business side if such scenario is needed.

@HRAGANBC @Joshua-Lakusta - FYI

**Comment by CarlyCotton** [comment]
@andrewsignori-aot Hiding FT Only programs is the expectation. Even if the Ministry mistakenly approves a PT offering for a FT only program.
