### ISSUE TITLE
Re-name the 'Upcoming Enrolment' Tab within Institution Account

### ISSUE THREAD

**Issue by HRAGANBC** [bcgov/SIMS#2530]
**Description of Task**
- Rename the tab called 'upcoming enrolment' 
- Add wording beneath the 'upcoming enrolment' tab header explaining what is reflected within this tab
- Possibly revise the logic of whether a COE request gets overwritten or not

**Acceptance Criteria:**
- [ ] Revise the tab name **from** "Upcoming Enrolment" **to**: "Upcoming and Previous Enrolments"
- [ ] Within the 'upcoming and previous enrolment' tab, add wording beneath the header which reads: "This page contains two types of records: 
- 1) disbursements requests which are upcoming and will be required at a later date. These are indicated by a 'Required' status
- 2) previously actioned Confirmation of Enrolment Requests which can no longer be actioned.  These are indicated by a 'Completed' status.

**Comment by sh16011993** [comment]
@CarlyCotton @Joshua-Lakusta Are the below bullet points ok?

<img width="1462" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmFJQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a0aaba598be2d4d8308df3cb4e38b94ad94ffde8/image.png" alt="image.png" />

**Comment by CarlyCotton** [comment]
@sh16011993 Can you please capitalize them?

**Comment by sh16011993** [comment]
Yes, will do. Thanks @CarlyCotton

**Comment by sh16011993** [comment]
@CarlyCotton  @Joshua-Lakusta @HRAGANBC Another quick question:

<img width="1918" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFdJQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c03cbfe340e9e444aa1735d7b51a94b0e13a252b/image.png" alt="image.png" />

We follow bold instead of quotes in other places in the application like below:

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGFJQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5d818be185b1e1c7cc6894bf726f5d65416c362a/image.png" alt="image.png" />

Should I change it from quotes to bold?
