### ISSUE TITLE
Program Validation - Online - BC Public/BC Private

### ISSUE THREAD

**Issue by CarlyCotton** [bcgov/SIMS#2623]
**User Story**
As an _institution user_ for a BC Public or BC Private institution, my online programs are eligible for SABC funding if they meet basic program requirements.

As an _institution user_ for an **out of province** institution, my online programs are subject to additional requirements to be eligible for SABC funding.

**Current Behaviour**
Creating a new program with any type of institution will prompt for additional questions when selecting "online" as a delivery option. This will continue to three additional questions to validate the program prior to creation.

**Expected Behaviour**
When creating a new program as a BC Public or BC Private institution, the following questions are not needed as they are only required to ensure the program meets the basic requirements.
When creating a new program as any _other institution type_, the following questions and logic should remain.
<img width="1146" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNTJKQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--56a7c63f9d9cd9af24ed98b348d9e8e1603bb88a/image.png" alt="image.png" />

**Acceptance Criteria**
- [x] Remove prompts for additional questions when "Online" program delivery is selected when being created by BC Public or BC Private institutions.
- [x] Keep prompts when creating an "Online" program (or Online and On site) for all other institution types.
- [x] No production adjustment is needed.

**Comment by CarlyCotton** [comment]
@HRAGANBC - Received this from Policy. It's creating pending programs for otherwise eligible ones. (More work for IPDT and frustration/delay for PSIs if not implemented) 

Not sure if you want to put in PT release or hold for after?

**Comment by HRAGANBC** [comment]
@CarlyCotton - thanks. 

I believe it would be technically simpler if the solution were just to change the back-end validation applied when BC schools explain the online component. 

This would mean the questions asked of ALL institutions are identical, BUT

BC schools face zero impact resulting from how they answer those questions, AND

Non-BC school programs enter pending status depending how they answer those questions. 

Is this still acceptable to policy? 

I am not opposed to your original solution, and it's worth proposing both to Devs since yours is cleaner overall.
