### ISSUE TITLE
Cancel Future Disbursements if COE is declined (Bug)

### ISSUE THREAD

**Issue by HRAGANBC** [bcgov/SIMS#2650]
**Related Tickets:**
#2677, #2676

**Context:**
- Assessment queues order will be dictated by the Assessment Date (i.e. assessment 1 conducted Sep 1 will consume all PY values, assessment 2 conducted Sep 2 will consume remaining PY values, regardless of study dates associated with those assessments)

**Description of Task:**
If COE is declined for any disbursement, then: 
- All future disbursements requests for that application should be automatically cancelled
- Student must re-submit their application to re-trigger a new COE request for the current application so they can get their money (Josh - I am thinking this could be solved with a new feature whereby Ministry staff can manually push through a new COE request without impacting the assessment. However, this would only apply if the student were making ZERO changes to their application which impacted assessment - anything impacting assessment would be definition create a new assessment, and have trickle down consequences for all others in queue). Alternatively, this assessment could be exempted from the trickle down sequence somehow?

**Current Behaviour:**
- When the first disbursement in an application has COE declined by Institution, the second disbursement is still active and gets requested of the school some time later. 

**Expected Behaviour:**
- As per Ticket #792, we'd expect that declining the first disbursement should cancel any future disbursements as well. 
- Context: If a COE request is declined by the Institution, the entire assessment is essentially 'terminated' in it's current state, and needs to be edited & re-submitted in order to trigger a new COE request.  

**Acceptance Criteria:**
- [x] Cancel the STATUS of all future disbursements when a COE is declined by the school
- [x] Decline future COEs when the first one is declined. 
- [x] Adjust the wording on the application status tracker card when COE is declined. Card should read: "Your institution declined your enrolment status. Reason from your institution: [insert]. All disbursements associated with this application have now been cancelled. To receive funding for this application, you must 'edit' your application and re-submit in order to allow your institution to Confirm your Enrolment again."_

**Technical Criteria**
- [x] e2e for cancelling the second the COE and declined status.

**Comment by andrewsignori-aot** [comment]
@HRAGANBC @CarlyCotton @Joshua-Lakusta about the AC that reads _Adjust the wording on the application status tracker card when COE is declined. Card should read: "Your institution declined your enrolment status. Reason from your institutions [insert]. All disbursements associated with this application have now been cancelled. To receive funding for this application, you must 'edit' your application and re-submit in order to allow your institution to Confirm your Enrolment again."_

It is my understanding that the content change will be applied only to the first COE canceled and the second COE content will remain as it is, right?
The content would not make sense either way for the second COE, as far as my understanding goes.

**Comment by andrewsignori-aot** [comment]
@HRAGANBC @CarlyCotton When the institution declines the COE SIMS generates the below notification.
<img width="760" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFdmQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ece9a99485f4d6ce8c82efe98907812940092618/image.png" alt="image.png" />

The fact that we will decline the second COE would not implicate sending two notifications (one per declined COE), right?
My assumptions:
1. If an application with 2 disbursements has the first one declined, only one notification is expected.
2. If an application with 2 disbursements has the second one declined, only one notification is expected.

**Comment by CarlyCotton** [comment]
@andrewsignori-aot 
The updated wording on the tracker "Your institution declined your enrolment status. Reason from your **institution:** [insert]. All disbursements associated with this application have now been cancelled. To receive funding for this application, you must 'edit' your application and re-submit in order to allow your institution to Confirm your Enrolment again." is great, I'll modify the AC to align with what you have there.

> The fact that we will decline the second COE would not implicate sending two notifications (one per declined COE), right?

Yes, the student should only receive one notification per institution "action" on their enrolment. One per confirmation, one per decline (even if the decline is on the first of two). In the case of 1st Confirmed and 2nd Declined, they would end up getting two notifications total.

**Comment by andrewsignori-aot** [comment]
### Demo

Institution: SIMS_COLLE
Student: Jack (SIMS00007)

Applications
- COE Approval Two Disbursements Offering (2023000504)
- COE Approval One Disbursement Offering (2023000505)

One small content to change `have` by `has` for a single disbursement.

**Comment by andrewsignori-aot** [comment]
Fixed content issue from the demo, as shown below.
<img width="940" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVNyQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1cb9dc3a3be948bf82fac6317bca1011f8d771f7/image.png" alt="image.png" />
