### ISSUE TITLE
Confirm Permanent Residency Expiry 

### ISSUE THREAD

**Issue by michesmith** [bcgov/SIMS#2721]

**Comment by michesmith** [comment]
@CarlyCotton @HRAGANBC  per convo with Steph could you dig in deeper on this?  Do we need a restriction on PR Expiry also the solutioning on this one is a bit strange? Should Citizenship be at the Profile Level. Which part of this is Part-Time vs Full scope Please Tag thank you :)

**Comment by HRAGANBC** [comment]
@michesmith @CarlyCotton 

This is a non-issue, as it's been designed to be handled by our SST staff rather than as a system solution / validation. 

To answer your specific question, citizenship is one of many eligibility criteria - eligibility criteria have been designed as 'exception questions' in SIMS to allow each decision to be adjudicated proactively as opposed to just outright deny people who don't meet all eligibility criteria and then resolve on appeal request.  There was also a design decision to make any such exceptions requests (formrly known as appeals) required for each _application_, consistent with current state, rather than making them attached to the profile (great idea for enhancement, but not critical). 

Process for handling PR expiry is as follows:
