### ISSUE TITLE
Application Changes Report(Type B report) - Analysis

### ISSUE THREAD

**Issue by dheepak-aot** [bcgov/SIMS#3207]
**Description of Task**
For application changes report #2499 Perform a technical analysis on processing the report ,  to store the `report processed status` for a given application(or assessment) and how to send the total number of records in file.

**Acceptance Criteria:**
- [ ] Create a technical solution, review with the team and update the technical solution to the ticket.
   The solution should be precisely describing the 
  - Processing of the report including how to store the report processed status of an application (or assessment)
  - How to send total number of records in the file.

**Comment by andrewsignori-aot** [comment]
## Draft Solution

### Create a new table `sims.application_reportable_changes`

The new table will keep the record of the last application reported and the ones to be reported.

#### Columns
- `application_id`: application id being reported.
- `first_reported_assessment_id`: first-ever assessment that had an e-Cert generated.
- changed_assessment_id: assessment where a reportable change was detected (e.g. offering dates). While the `date_sent` is `null` this can be updated with a most recent change.
- date_sent (null): set when the changes were reported to NSLC. All records sent as part of the same file should have the same date.

**Comment by andrewsignori-aot** [comment]
# Draft Solution (B)

## Create new columns in table `sims.applications` or `sims.student_assessments`.

Two new columns will keep track of the last reported change to NSLSC. When the `assesssment_id` between the two columns is different it means that a change must be reported to the NSLSC.
Note:
1. _Multiple reassessments can happen in a way that the assessment would be changed to its original dates and there will be no need to it be reported._
2. Instead of new columns in an existing table a one-to-one table could be created.

### Columns
- `application_id`: application id being reported.
- `first_reported_assessment_id`: first-ever assessment that had an e-Cert generated.
- `changed_assessment_id`: assessment where a reportable change was detected (e.g. offering dates). While the `date_sent` is `null` this can be updated with a most recent change.
- `date_sent` (nullable): set when the changes were reported to NSLC. All records sent as part of the same file should have the same date.
 
### When the table will be populated?
 
The process to populate `sims.application_reportable_changes` must happen at the same time e-Cert records are marked as sent and in the same DB transaction.

- Disbursements to be checked
  - `Status` as `Sent`.
  - Not original assessment. Original assessments will never have dates changed.
  - Never sent a disbursement before. If one disbursement was already sent for an assessment the change is already reported or to be reported.

- Process
  - Get the most recent `sent` record from `sims.application_reportable_changes` for the application.
  - TODO: continue!
  
## CSV Generation

The CSV generation will be entirely based on the `sims.application_reportable_changes` where the `date_sent` is `null`. The scheduler will be executed and always search for any record that was never reported. This will ensure that the scheduler can be executed at any time and every change detected will be reported.

There will be no need to know when the last report was executed since the `date_sent` as `null` will indicate all records that must be reported.

## Total Record Number

The total records number can be appended to the end of the file without harm to the CSV format. It will be considered as a value in the first column.

**Comment by andrewsignori-aot** [comment]
# Draft Solution (C)

## Create new columns in table `sims.applications`.

Two new columns will keep track of the last reported change to NSLSC. When the `assesssment_id` between the two columns is different it means that a change must be reported to the NSLSC.
Note:
1. _Multiple reassessments can happen in a way that the assessment would be changed to its original dates and there will be no need for it to be reported._
2. Instead of new columns in an existing table a one-to-one table could be created.

### Columns
- `last_reported_assessment_id`: last time that this application was reported to NSLSC, either because the first e-Cert was generated or because it had its offering dates changed.
- `last_reported_changed_assessment_id`: last assessment id reassessed that caused a change in offering dates.

#### Assessment offering change detection

1. During the `workflow-wrap-up` worker processing, check if the assessment has different dates from the `last_reported_assessment_id`.
1.1 If `yes`, update the `last_reported_changed_assessment_id` to the current assessment being processed.
1.2 If `no`, check if the `last_reported_assessment_id` is the same as the `last_reported_changed_assessment_id`, if not, update it. The assessment can have the dates changed in a way that would be again the same as the last report, which means that no change needs to be reported.

## CSV Generation

The CSV generation will be entirely based on the two new columns. There is no need right now to keep any history of the generated report.
1. The application should be included in the report when the two columns have different IDs.
2. Once the report is generated the  `current_reported_assessment_id` must be updated with the value from `last_changed_assessment_id`.
 
_Notes_

1. This will ensure that the scheduler can be executed at any time and every change detected will be reported.
2. There will be no need to know when the last report was executed since the `date_sent` as `null` will indicate all records that must be reported.

## Total Record Number

The total records number can be appended to the end of the file without harm to the CSV format. It will be considered as a value in the first column.

**Comment by andrewsignori-aot** [comment]
# Draft Solution (D)

## Create new columns in table `sims.student_assessments`.

TO DO as per the last meeting.

**Comment by andrewsignori-aot** [comment]
@HRAGANBC This analysis generated ticket #3282 which will need to be done before the final implementation of #2499.
Both #3282 and #2499 are now estimated and ready for the sprint.
@sslaws if @HRAGANBC is ok we can close this ticket.

**Comment by HRAGANBC** [comment]
@sslaws @andrewsignori-aot 

OK with me to close this ticket. Thanks for the explanation of next steps.
