### ISSUE TITLE
UX/ UI- Cont. V2 Institution Onboarding and Designation Wireframe

### ISSUE THREAD

**Issue by mzmichellesmith** [bcgov/SIMS#327]
- [ ] Fine Tune and QA the content and formatting a team
- [ ] Any updates as required per conversations with SMEs

**Comment by roopfw** [comment]
Working to include multiple locations and moving primary contacts to locations and moving legal signing authority for Institution level to user role selection page

**Comment by roopfw** [comment]
**Changes made after PO review 1:**
- Primary Location holds Institution’s address
- Moved Primary Contact to Institution's account level
- Kept Legal Authority Selection on this screen since it feels like a detail of the location rather than a role selection detail. Especially if there are multiple locations
- Adjusted to show multiple locations when adding initial programs with ability to save/edit/copy to another location
- Shows which locations still require a program to be added/have had programs added
- Updated roles page to also allow for location selection
- Locked roles based on information entered on profile setup step. (Primary contact for location automatically receives admin role)


Institution Account (Primary Contact and Legal Authority)
* Primary Location 1
* Location 2

**Changes made after PO review 2:**
* Move primary contact back to Institution level info 
    * with the ability to add location-based contact.
* If they have a code already from a different province allow them to enter it during the application phase
* Legal authority message to say these users need to abide by the whatever agreement “Confirm Users”
* Allow school to add master designation list code for Institution at EACH location if they have one.
