### ISSUE TITLE
UX Institution EDITING details and Locations

### ISSUE THREAD

**Issue by mzmichellesmith** [bcgov/SIMS#331]
Additional Context
- This is an analysis and design ticket
- Institution users should and should not be able to edit certain information. Information that is not editable by and institution should be managed by the ministry staff, either though a simple edit or a "request"
- If possible, use same workflow for outcome of tix #862 (request changes to program/offering)
- Keep in mind the ministry UX (a further ticket may need to be created for this)
- Touchbase with Phil

**Acceptance Criteria**
- [ ] Analysis of every field in the below areas for an institution to determine: (Is it editable, if not, how does it get changed (request/ministry change))
- Institution details (account-level)
- Institution Locations
- [ ] Note any field that does not have a mechanism to change
- Either mock it up how it would get changed, or 
- Create separate ticket if it needs to be a feature

**Comment by abschwenker** [comment]
from Jan 07. You cannot add offering to a denied program. Students cannot apply for a pending program. You CAN add an offering to a pending program (warning banner maybe?)

**Comment by abschwenker** [comment]
locations can only create offerings between location DA start date to Expiry date

**Comment by abschwenker** [comment]
institution code not editable by institutions
institution address not editable by institutions

**Comment by hellolynn-dsib** [comment]
Lynn meet with Phil - Mon 14 to wrap up for Tues 15

**Comment by abschwenker** [comment]
Option 1:
Impliment queue system for institutions requesting changes to institution details
Impliment queue system for institutions requesting changes to location details
Open questions: 
what to do with transient data
rules for intransit recrods and downstream impacts (ie. application, assessment, etc)

Option 2:
Institutions can not edit institution details
Institution can not edit location details
New funcationality to allow ministry users to edit all institution details (required even if we chose option 1)
New funcationality to allow ministry users to edit all location details (required even if we chose option 1)

Due to too many downstream impacts, option 2 will be initial workload, additional feature requests may come in
