### ISSUE TITLE
Determine CRA Integration Readiness/ Determine Implementation Plan

### ISSUE THREAD

**Issue by mzmichellesmith** [bcgov/SIMS#347]
Additional Context:
We use Canada Revenue Agency (CRA) for SIN Validation and Income Validation

Tasks
- [x] Schwenker to give a high-level overview
- [x] Validate CRA Documentation- check calls that they have provided.
- [ ] Verify the ability to Run CRA Service (entrust) in Openshift - Not possible at this time

Acceptance Criteria
- [x] Determine Endstate Architecture Option
- [x] Determine Implementation Next Steps (Plan)
- [x] Update Architectrue Diagram

**Comment by andrewsignori-aot** [comment]
**Summary**
The current architecture plan would be to continue to use the same process to send files to CRA that is already working under Zone B and is currently being used by SFAZ.
in order to do it, an SFTP server will be enabled on Zone B and the necessary connectivity between OpenShift and this SFTP on Zone B will be enabled.

**Considerations to enable SFTP on Windows Server**
Depending on the Windows Server version, the SFTP will be available as a Windows Feature, if not available, additional steps are needed but both methods are going to end up in the same result.
For Windows Server 2016, build 1709 or newer:
- Enable SSH Server Feature as described in here: https://techcommunity.microsoft.com/t5/itops-talk-blog/installing-and-configuring-openssh-on-windows-server-2019/ba-p/309540
For Windows Server 2016, older than build 1709:
- Enable SSH Server as described here: https://github.com/PowerShell/Win32-OpenSSH/wiki/Install-Win32-OpenSSH

Both way are going enable the following:
- Windows Service named sshd (OpenSSH SSH Server)
- Windows Service named ssh-agent (OpenSSH Authentication Agent)
Please ensure that both windows services are configure for Automatic startup type and some recovery options.

**Considerations about STFP configurations**
Main sshd server config present on: C:\ProgramData\ssh\sshd_config
Uncomment and configure the property ChrootDirectory to limit the folders that are accessible via SFTP. Also consider further investigation about using sftp-server vs internal-sftp.
Uncomment and configure the property PasswordAuthentication to "no" to force only key authentications to happen.

Use the below reference to help to configure the private/public key for SSH access.
https://www.concurrency.com/blog/may-2019/key-based-authentication-for-openssh-on-windows
Please note that Files that store authorized_keys should have specific permissions. This is mentioned in the above link
that also contains the below powershell script that could help with the adjustments.

$acl = Get-Acl C:\ProgramData\ssh\administrators_authorized_keys
$acl.SetAccessRuleProtection($true, $false)
$administratorsRule = New-Object system.security.accesscontrol.filesystemaccessrule("Administrators","FullControl","Allow")
$systemRule = New-Object system.security.accesscontrol.filesystemaccessrule("SYSTEM","FullControl","Allow")
$acl.SetAccessRule($administratorsRule)
$acl.SetAccessRule($systemRule)
$acl | Set-Acl

Consider checking below instructions to only allow SFTP via SSH (section "Modify SSH Configuration File").
https://www.tecmint.com/restrict-sftp-user-home-directories-using-chroot/

**Considerations about an STFP nodejs library**
A POC was made using the npm ssh2-sftp-client (https://www.npmjs.com/package/ssh2-sftp-client)
This library also conatins the type available @types/ssh2-sftp-client (https://www.npmjs.com/package/@types/ssh2-sftp-client)
The POC was able to create an SFTP client connecting using private/public keys and create folder and files on SFTP server.
