### ISSUE TITLE
Bug Fix for error in workers pods

### ISSUE THREAD

**Issue by guru-aot** [bcgov/SIMS#3502]
It seems there is some error when the camunda tries to connect with the zeebe libraries configurations, but this is not related to the health check or the process running in workers. Currently we are not facing any downtime or queue processing delays due to the above error. I also confirm there is no crash loop error happening in any of the environments/namespaces.
Also the restart was happening like 3 time from July 4, which is normal and not due to this issue or the health check.

The issue may be a cause of the library used for health check by our health indicator https://github.com/bcgov/SIMS/blob/7b072e5ca8ccc40bb693743385d877ef2c02431c/sources/packages/backend/apps/workers/src/zeebe/zeebe-health-indicator.ts? 
It can be also the camunda_outh_url which has been updated as part of last release Release v1.9.0.

PFB the processing logs.

<img width="1401" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0hNQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5f4aaa743b4887cdd7bf2333283b52ab08977ef6/image.png" alt="image.png" />

<img width="1425" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMnZTQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--433391976304d7f9da27dcc529b5578598a47aab/image.png" alt="image.png" />

**Comment by andrewsignori-aot** [comment]
## Analysis
 The cancellation error seems to be generated due to conflicted configurations with their default values set to 60s.
- `ZEEBE_GRPC_WORKER_LONGPOLL_SECONDS`: how long in seconds the long poll Job Activation request is held open by a worker.
- `DEFAULT_JOB_ACTIVATION_TIMEOUT`:  timeout for the GRPC call to activate a job.

With both variables set to 60s, the `DEFAULT_JOB_ACTIVATION_TIMEOUT` throws the cancellation error when the timeout is reached.

### Proposed solution

Set the variables as below to allow the long pooling to restart before the job activation reaches its timeouts.
- ZEEBE_GRPC_WORKER_LONGPOLL_SECONDS: 60
- DEFAULT_JOB_ACTIVATION_TIMEOUT: 65

The above configuration was tested on DEV manually adding the variables and it solved the problem. Further investigation will be done.
