### ISSUE TITLE
Rough Reshape of FT Assessment and DMN

### ISSUE THREAD

**Issue by CarlyCotton** [bcgov/SIMS#3622]
**User Story**
As a ministry user, I want to do an end to end update of the entire FT assessment calculation (including DMN tables) to get the assessment closer to what is expected. This will allow us to spend more time on the small details and confirming policy rather than identifying the gaps.

**Acceptance Criteria**
- [x] Update the ft assessment decision dmn file: [DEVS>BPM Workflows>3622 - FT Assessment and DMN](https://bcgov.sharepoint.com/:u:/r/teams/03177/Shared%20Documents/DEVS/BPM%20Workflows/3622%20-%20FT%20Assessment%20and%20DMN/fulltime-assessment-2024-2025.bpmn?csf=1&web=1&e=kJ5fpH)
- [x] Update the ft assessment 2024-2025: [DEVS>BPM Workflows>3622 - FT Assessment and DMN](https://bcgov.sharepoint.com/:u:/r/teams/03177/Shared%20Documents/DEVS/BPM%20Workflows/3622%20-%20FT%20Assessment%20and%20DMN/fulltime-assessment-decisions.dmn?csf=1&web=1&e=lNaes4)
    - [x] Copy this same flow for all other FT years 22-23 & 23-24
    - [x] Make sure it generates NOA
    - [x] Check for any missing variables
    - [x] It may break any e2e FT tests but they will need to be re-written when closer to a more accurate calculation

**Technical**
- [x] Replace the `fulltime-assessment-decisions.dmn` with the provided one.
- [x] Replace the `fulltime-assessment-*.bpmn` files with the provided one adjusting the necessary year-related IDs.
- [x] Ensure full-time applications are still submitted and generate the NOA.
- [x] Make the E2E tests pass adjusting any expected value.

**Comment by dheepak-aot** [comment]
@CarlyCotton as per our discussion regarding the list of DMN declared names and usage, sharing the information here. 

dmnFullTimeCalculatedDataLivingCategory - Declared but not used.

dmnFullTimeCalculatedDataProgramYearMaximums - Declared and used with Wrong reference. (dmnFullTimeProgramYearMaximums) (This is taken care and fixed in PR by @lewischen-aot )

dmnFullTimeCalculatedDataIncomeThreshold - Declared and used with correct reference.

dmnFullTimeCalculatedDataApplicationBooksMaximum - Declared but not used.

dmnFullTimeCalculatedDataApplicationtransportationMaximum - Declared and used with correct reference.

dmnFullTimeCalculatedDataStudentMSOLAllowance - Declared and used with correct reference.

dmnFullTimeCalculatedDataDependantMSOLAllowance - Declared and used with correct reference.

dmnFullTimeCalculatedDataParentsMSOL - Declared and used with correct reference.

dmnFullTimeAwardFederalAllowableLimits and dmnFullTimeAwardProvincialAllowableLimits renamed to dmnFullTimeAwardAllowableLimits

dmnFullTimeAwardAllowableLimits - Declared and used with correct reference.

dmnFullTimeAwardFamilySizeVariables- Declared and used with correct reference.

Some DMN references are declared with `calculatedData` in it(7 of them) and some without(3 of them). The naming difference has been there from the beginning(long back). 

For PT we have not used the convention of `calculatedData`. 
Fixing the declared names wouldn't be part of this effort and we can do that in one of the upcoming efforts.

**Comment by dheepak-aot** [comment]
To share the knowledge here. 
There is a behavior difference in DMN output, when the dmn returns one property vs multiple properties. Due to this, dmn was returning null in some areas. 

Please take a look at this PR comment. It has all the details.

https://github.com/bcgov/SIMS/pull/3772#discussion_r1796197990
