### ISSUE TITLE
UX/ UI- Dev/ Architecture- Create Institution Account Structural View Site Map

### ISSUE THREAD

**Issue by mzmichellesmith** [bcgov/SIMS#366]
Determine  how does the account interact with Locations
Connect with Jamie and Andrew to validate the structure.

**Comment by hellolynn-dsib** [comment]
Quick sketch from Alys ![MicrosoftTeams-image (3).png](https://images.zenhubusercontent.com/6047d6ac906f4ec904f7286c/358123c6-e15e-41e0-9b7c-f7e74d91b06b)

**Comment by alpivett** [comment]
Acceptance Criteria:
- 1 page schema (picture) that depicts the Institution Account and Institution Location relationships and the screens accessed through each (includes Users, Students, Programs))
- Refine reusable language
- the output will be inserted in to future communications and training material - ensure it is exportable

**Comment by hellolynn-dsib** [comment]
**Recap**

- Meeting 1: Site map draft review with Schwenker
- Meeting 2: Lynn/Schwenker working sesh
- Meeting 3: Defining account structure & roles (shared understanding to move forward)

 
**Mural:** https://app.mural.co/t/range1280/m/range1280/1618511077891/73d35d0fb753bb324fa338cc76c81336f2b071da

**Outcome:**
- Defined role names (internal) - to help differiente (Owner/legal signer - Institution account admin - Location manager)
- Tickets/pages to build (within MVP scope)
- Read-only (to follow up with institutions/build last in MVP - 0 read only logins since Jan 2021)
- Simplified site map (#366)

_Crosspost in UX/UI teams channel_

**Comment by hellolynn-dsib** [comment]
Ready for UX connect.

**Comment by hellolynn-dsib** [comment]
**UX connect outcome:**

- Additional AC: add functionality to help describe relationship (VIEW, EDIT, ADD, REMOVE)
- To revisit tomorrow: "manage institution" label - how does it sound for business/tech consideration?

**Comment by hellolynn-dsib** [comment]
**UX connect outcome:**

- Alys/Schwenker working sesh
- Lynn/Schwenker working sesh to beautify
- UX connect quick review with group
- DONE

**Final copy:**
https://app.mural.co/t/range1280/m/range1280/1617814069573/f58a9c9190f2fe03a8e774a70059fc667eec369d
