### ISSUE TITLE
View Assessment Updates

### ISSUE THREAD

**Issue by JerPearson** [bcgov/SIMS#3697]
As a student I want the summary page to show show accurate award information.

**Acceptance Criteria**

- [x] Revise: "Summary" to "Funding summary"
- [x] Revise: "To view your entire assessment....." to "To view your Notice of Assessment, click on view assessment".
 - [x]  Format all values: $##,###.00
- [x] Update the following grant names, reorder based on the list below, apply changes to both estimated and final award.

**CSGP**
- [x]  Revise: "CSGP" to "CSG-PD" 
- [x]  Update tooltip: "Canada Student Grant for Students with Disabilities"

**CSPT**
- [x]  Revise: "CSPT" to "CSG-PT" 
- [x]  Update tooltip: "Canada Student Grant for Part-time Students" 

**CSGD**
- [x]  Revise: "CSGD" to "CSG-PTDEP"  
- [x]  Update tooltip: "Canada Student Grant for Students with Dependants"

**BCAG**
- [x]  Revise: "BCAG" to "BCAG-PT"
- [x]  Update tooltip:  "B.C. Access Grant for Part-time Studies"

**CSLP**
- [x] Revise: "CSLP" to "CSL-PT" 
- [x] Update tooltip: "Canada Student Loan for Part-Time Students"

**SBSD**
- [x]  Update SBSD tooltip: "B.C. Supplemental Bursary for Students with Disabilities"

<img width="1147" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekR4Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c46d308234b31c84199e778397c90be13d073b09/image.png" alt="image.png" />

- [x] When multiple disbursements, the estimated award category is duplicated to show multiple awards.  Revise "First payment" to "First disbursement" and "Second payment" to "Second disbursement"

<img width="431" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNEg3Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0174574548013d6bd25487a421c635190b2662a0/image.png" alt="image.png" />

**Comment by lewischen-aot** [comment]
@CarlyCotton I managed to display final awards for the following applications whose numbers are 2023000550 and 2023000519 for the student user SIMS00004 on DEV. 

Application number 2023000550 
<img width="1567" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUY3Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1f0105599068821ae56cc324050a3a4c391f97ea/image.png" alt="image.png" />

Application number 2023000519
<img width="1694" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWw3Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c012cc14b98b4ab2c375410ffe8e547ab49d450e/image.png" alt="image.png" />

The next screenshots from an application in my local environment is shown here because it has both first and second payment, which are missing from the above ones.
<img width="1235" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmg3Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ad63db318637bcf6c471c9f090533028423f6b34/image.png" alt="image.png" />
<img width="1186" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmw3Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9a83393ece6fb6d109dee3a3ff4bc9fb23a52957/image.png" alt="image.png" />

**Comment by lewischen-aot** [comment]
@CarlyCotton I managed to display final awards for the following applications whose numbers are 2023000550 and 2023000519 for the student user SIMS00004 on DEV. 

Application number 2023000550 
<img width="1567" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUY3Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1f0105599068821ae56cc324050a3a4c391f97ea/image.png" alt="image.png" />

Application number 2023000519
<img width="1694" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWw3Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c012cc14b98b4ab2c375410ffe8e547ab49d450e/image.png" alt="image.png" />

The next screenshots from an application in my local environment is shown here because it has both first and second payment, which are missing from the above ones.
<img width="1235" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmg3Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ad63db318637bcf6c471c9f090533028423f6b34/image.png" alt="image.png" />
<img width="1186" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmw3Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9a83393ece6fb6d109dee3a3ff4bc9fb23a52957/image.png" alt="image.png" />

**Comment by CarlyCotton** [comment]
@lewischen-aot Thanks Lewis. Verified with @JerPearson it's good to go. Closing.
